package com.amazon.milan.aws.serverless.compiler

import com.amazon.milan.application.ApplicationInstance
import com.amazon.milan.compiler.scala.event.GeneratedStreams


/**
 * Information about the source of events for a stream.
 *
 * @param eventSource          The event source type, e.g. "aws:sqs" or "aws:dynamodb".
 * @param streamId             The ID of the stream.
 * @param eventSourceArnPrefix The prefix of the event source ARN, used to determine which records in the lambda event
 *                             correspond to the stream.
 */
case class StreamEventSource(eventSource: String, streamId: String, eventSourceArnPrefix: String)


/**
 * Contains contextual information for generating AWS serverless components to execute a Milan application.
 *
 * @param application                  The Milan application instance being compiled.
 * @param eventSources                 Describes the event sources for the input streams.
 * @param eventHandlerGeneratedStreams Information about the streams that were generated by the scala event compiler.
 */
case class AwsGeneratorContext(application: ApplicationInstance,
                               eventSources: List[StreamEventSource],
                               eventHandlerGeneratedStreams: GeneratedStreams)
