package com.amazon.milan.compiler.scala.event


/**
 * An interface that is implemented by classes generated by the [[EventHandlerClassGenerator]].
 *
 * It allows callers to send in data records by referencing name of the stream that the record is for.
 */
trait RecordConsumer {
  def consume(inputName: String, value: Any): Unit
}
